# Generated by Django 3.2.8 on 2024-04-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FilePathField(blank=True, null=True, path='/uploads'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
