# Generated by Django 3.2.3 on 2024-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240417_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
