# Generated by Django 3.2.3 on 2024-04-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240424_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
