# Generated by Django 5.1.6 on 2025-04-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_posts_likes_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=models.ManyToManyField(blank=True, to='app.comment'),
        ),
    ]
