# Generated by Django 5.1.6 on 2025-04-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_posts_likes_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
