# Generated by Django 5.1.6 on 2025-04-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_commentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FilePathField(blank=True, null=True, path='uploads/'),
        ),
    ]
