# Generated by Django 5.1.6 on 2025-04-07 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='app.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=models.ManyToManyField(blank=True, to='app.comment'),
        ),
    ]
