# Generated by Django 5.2.11 on 2026-03-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_friend_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
