# Generated by Django 5.2.11 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_posts_created_posts_is_story_alter_posts_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_reel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
