# Generated by Django 5.2.11 on 2026-03-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_toxic_comment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
