# Generated by Django 5.2.11 on 2026-03-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_profile_last_toxic_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_ban_applied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
